apiVersion: apps/v1
kind: Deployment
metadata:
  name: sending-deployment
  namespace: helm-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sending
  template:
    metadata:
      labels:
        name: sending
    spec:
      containers:
        - name: basketball-sending-container
          image: anarchyghost/sending
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service.helm-deployments:8080/eureka"
            - name: EUREKA_INSTANCE_PREFERIPADDRESS
              value: "true"