# Application-wide configuration
server:
  port: 8080

spring:
  application:
    name: Eureka Server
  security:
    user:
      name: user
      password: bestpasswordever
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
