# Application-wide properties
server:
  port: 8002

spring:
  # Set the name of application
  application:
    name: sending

# Configuring Eureka client, at this moment it's necessary to show where Eureka is located
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:bestpasswordever@localhost:8000/eureka