app:
  kafka:
    topics:
      auth:
        codeRequested: auth_code_requested
        codeCreated: auth_code_created

spring:
  kafka:
    bootstrap-servers: 146.185.208.133:9092
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration