app:
  kafka:
    server: http://localhost:9092
    topics:
      auth:
        codeRequested: auth_code_requested
        codeCreated: auth_code_created

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration